### ISSUE TITLE
Can a new version be released?

### ISSUE THREAD

**Issue by danehammer** [opscode-cookbooks/sudo#64]
2.7.1 was released 6 months ago, but master shows the same version in the metadata. What is required to cut a 2.8 release with this change 215145c949d, from August?

Can the metadata in master be bumped to a new version after release?

**Comment by danehammer** [comment]
To be clear, let me know how I can help. If you want me to do the tagging, verifying, uploading to the supermarket.

**Comment by wifflebob** [comment]
+1 on this. I'm waiting on the same change in a new release.

**Comment by miketheman** [comment]
:+1: Also waiting for this to be released - anything we can do to push this forward?

**Comment by miketheman** [comment]
2.7.2 released yesterday. @someara thanks, and feel free to close this issue!
